### PR TITLE
add custom percent opacity

### PR DESCRIPTION
**Pull request by Miguel0101**
Add custom percent opacity, eg: `lv_opa_pct(45)`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Good idea, but it should be implemented as a function too because defines are not seen by the MicroPython binding. 

I wonder if `LV_OPA_PCT(45)` would be more intuitive. 
Note that for coordinates we have simply `lv_pct()` which offsets the percentage to a very large value and if LVGL sees such a large coordinate it knows if it's a percentage. 

So `lv_opa(lv_pct(45))` could also work but it seems a little bit cumbersome. 

@embeddedt , @xiaoxiang781216 What do you think?

**Comment by Miguel0101** [comment]
> Good idea, but it should be implemented as a function too because defines are not seen by the MicroPython binding.
> 
> I wonder if `LV_OPA_PCT(45)` would be more intuitive. Note that for coordinates we have simply `lv_pct()` which offsets the percentage to a very large value and if LVGL sees such a large coordinate it knows if it's a percentage.
> 
> So `lv_opa(lv_pct(45))` could also work but it seems a little bit cumbersome.
> 
> @embeddedt , @xiaoxiang781216 What do you think?

Sounds good to me.

**Comment by embeddedt** [comment]
Hmm, I'm not sure about this. We already provide percentage enums in increments of 10 for opacity. What is the advantage of having yet another function/macro, as opposed to someone just picking a value between 0 and 255 if they want more precision?

**Comment by Miguel0101** [comment]
> Hmm, I'm not sure about this. We already provide percentage enums in increments of 10 for opacity. What is the advantage of having yet another function/macro, as opposed to someone just picking a value between 0 and 255 if they want more precision?

You're right, but if the user wants a percentage value that isn't included in the `enum`, he could use the `lv_opa_pct` function to put in a percentage value.

**Comment by kisvegabor** [comment]
My only problem with `lv_opa_pct()` is that it's not consistent with the naming of `lv_pct()`. 

Thinking about it more adding, I'm afraid of confusing the API and naming with it.

If there is no objection I'd rather not merge it. The user can easily use `value * LV_OPA_COVER) / 100);` manually, or add this macro himself if needed.

**Pull request closed without merging**
