### PR TITLE
Update unit tests

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Updates existing unit tests with changes done in #2623, like no longer needing function prototypes and having `setUp` and `tearDown` functions available.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
I think it should pass CI now, can it be manually triggered?

**Comment by embeddedt** [comment]
I believe you need to rebase your `update_tests` branch on our `master` branch and then force-push it. It's missing #2623 which allows prototypes to be skipped.

**Comment by C47D** [comment]
> I believe you need to rebase your `update_tests` branch on our `master` branch and then force-push it. It's missing #2623 which allows prototypes to be skipped.

You're right

**Comment by C47D** [comment]
This is the failing test, on the assert both `initial_available_memory` and `m1.free_size` are the same, I guess it's expected?

```c
void test_checkbox_should_allocate_memory_for_static_text(void)
{
    uint32_t initial_available_memory = 0;
    const char *static_text = "Keep me while you exist";

    lv_mem_monitor_t m1;
    lv_mem_monitor(&m1);

    initial_available_memory = m1.free_size;

    lv_checkbox_set_text_static(checkbox, static_text);

    lv_mem_monitor(&m1);

    TEST_ASSERT_LESS_THAN(initial_available_memory, m1.free_size);
}
```

This is the diff with previous version:
```diff
@@ -80,9 +73,6 @@ void test_checkbox_should_allocate_memory_for_static_text(void)
     lv_mem_monitor_t m1;
     lv_mem_monitor(&m1);

-    active_screen = lv_scr_act();
-    checkbox = lv_checkbox_create(active_screen);
-
     initial_available_memory = m1.free_size;

     lv_checkbox_set_text_static(checkbox, static_text);
```

Is the `checkbox` creation removal saving memory?

**Comment by embeddedt** [comment]
I think so. `lv_checkbox_set_text_static` is not supposed to allocate anything as far as I know.

**Comment by C47D** [comment]
> I think so. `lv_checkbox_set_text_static` is not supposed to allocate anything as far as I know.

Thanks for the info, I've updated the test

**Comment by kisvegabor** [comment]
Looks good to me. Is it ready to merge?

**Comment by C47D** [comment]
Yes it is

**Comment by kisvegabor** [comment]
Thank you, Carlos.

**Pull request merged**
