### PR TITLE
[rt-thread] add support for rt-thread RTOS

### PR DESCRIPTION
**Pull request by mysterywolf**
### Description of the feature or fix

Hi,

Thanks for your amazing project! This PR is for supporting RT-Thread Real-Time Operating System. Lvgl will be registered to the RT-Thread software packages center. RT-Thread has supported more than 200 boards (https://www.rt-thread.io/board.html). 

This PR includes two Sconscript files. RT-Thread uses Scons to organize files rather than CMake or Makefile, so it will not cause any conflicts with Lvgl CMake files.

I would be grateful if you consider about this PR. Thanks ahead.

Meco

https://github.com/RT-Thread/rt-thread
https://www.rt-thread.io

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Amazing, thank you!

> Lvgl will be registered to the RT-Thread software packages center.

Do we need to anything on releases or the new versions are picked automatically?

---

Could you add a new file to the [Get started](https://docs.lvgl.io/master/get-started/index.html) section of the [docs](https://github.com/lvgl/lvgl/tree/master/docs/get-started) for rt-thread and write a few lines about how to get started with it and LVGL?

**Comment by mysterywolf** [comment]
> Could you add a new file to the Get started section of the docs for rt-thread and write a few lines about how to get started with it and LVGL?

Hi, yes, but this will move to the next PR. The first PR will make sure that Lvgl will have been registered to RT-Thread software package center. Then, I will write some documents to demonstrate how to use Lvgl in RT-Thread. Thank you.

**Comment by mysterywolf** [comment]
> Do we need to anything on releases or the new versions are picked automatically?

Nop, you don't need to do anything, just follow your original release plan. RT-Thread side will not interfere with your release plan. RT-Thread side has a robot to handle this kind of things in the software packages center automatically.

**Comment by kisvegabor** [comment]
Great, I merge it then.

**Comment by kisvegabor** [comment]
Thank you again :slightly_smiling_face:

**Comment by mysterywolf** [comment]
Thank you very much!😁

**Pull request merged**
