### PR TITLE
build add install rule to CMakeList.txt (#2621)

### PR DESCRIPTION
**Pull request by rzr**
* build: Add install rule

This can help to install lvgl on systems,
for clients applications.

It's made for unix (Linux OE/Yocto actually)
if needed it can be enabled for other platforms too.

Relate-to: https://github.com/lvgl/lvgl/issues/2534
Forwarded: https://github.com/lvgl/lvgl/pull/2621
Signed-off-by: Philippe Coval <philippe.coval@astrolabe.coop>

* build: Make install rules optionnal

This change may be reverted, once verified it's harmless

It was tested using:

    cmake -Dinstall=ON . && make install DESTDIR=/tmp/

Forwarded: https://github.com/lvgl/lvgl/pull/2621
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you!

Do you think we should mention the `install` option in the docs somewhere?

**Comment by rzr** [comment]
yes I plan to update doc for next release (I promise :) ) , for I need to verify everything is building as expected, so this merge would help for that

BTW do you have any short vision of next release because it can be safer for support this branch meanwhile,
if it work as expected maybe I'll update OE to downgrade to this version

**Comment by kisvegabor** [comment]
> yes I plan to update doc for next release (I promise :) ) , for I need to verify everything is building as expected, so this merge would help for that

Great, thank you :slightly_smiling_face: 

> BTW do you have any short vision of next release because it can be safer for support this branch meanwhile,
if it work as expected maybe I'll update OE to downgrade to this versio

IMO we can make a release soon. I commented about it [here](https://github.com/lvgl/lvgl/issues/2573#issuecomment-945629793).

**Comment by kisvegabor** [comment]
We are getting closer to the release and I reviewing open PRs.

I merge this, if there is regressing it should turn out in the upcoming days.

**Pull request merged**
